### ISSUE TITLE
where can i get the brain data and mask?

### ISSUE THREAD

**Issue by brisyramshere** [sergivalverde/sub-cortical_segmentation#3]
I want to know can I get the traning data for free on internet?

**Comment by sergivalverde** [comment]
IBSR data can be found here:

https://www.nitrc.org/projects/ibsr

But then, MICCAI2012 data seems to be offline now. I don't if some repository exists for this

**Comment by wanglinwangyinuo** [comment]
Can this program be tested with IBSR datasets?

**Comment by wanglinwangyinuo** [comment]
Is the name of ROI the name of the label?

**Comment by sergivalverde** [comment]
> Can this program be tested with IBSR datasets?

Yes

**Comment by sergivalverde** [comment]
> Is the name of ROI the name of the label?

Yes it is.
